version: "3.8"

services:

  product-postgres:
    image: postgres:16
    container_name: classy-product-postgres
    restart: always

    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: productdb

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U product_user -d productdb"
        ]
      interval: 10s
      timeout: 5s
      retries: 10

    ports:
      - "5433:5432"

    volumes:
      - product_postgres_data:/var/lib/postgresql/data

    networks:
      - classy-network

  redis:
    image: redis:7
    container_name: classy-redis
    restart: always

    ports:
      - "6379:6379"

    volumes:
      - redis_data:/data

    networks:
      - classy-network

  kafka:
    image: apache/kafka:latest
    container_name: classy-kafka
    restart: always

    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093        #node-id@host:port
      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://classy-kafka:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      # KRaft cluster id
      CLUSTER_ID: MkU3OEVBNTcwNTJENDM2Qk

    volumes:
      - kafka_data:/var/lib/kafka/data

    ports:
      - "9092:9092"

    networks:
      - classy-network

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: classy-kafka-ui
    restart: always

    environment:
      KAFKA_CLUSTERS_0_NAME: classy-kafka
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: classy-kafka:9092
      KAFKA_CLUSTERS_0_PROPERTIES_SECURITY_PROTOCOL: PLAINTEXT

    depends_on:
      - kafka

    ports:
      - "8085:8080"

    networks:
      - classy-network

  discovery-server:

    build:
      context: ./discovery-server
    
    container_name: classy-discovery-server
    restart: always

    ports:
      - "8761:8761"

    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8761/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 10

    networks:
      - classy-network

  config-server:

    build:
      context: ./config-server

    container_name: classy-config-server
    restart: always

    ports:
      - "8888:8888"

    volumes:
      - ./config-repo:/config-repo

    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8888/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 10

    depends_on:
      - discovery-server

    networks:
      - classy-network

  api-gateway:

    build:
      context: ./api-gateway

    container_name: classy-api-gateway

    restart: always

    ports:
      - "8080:8080"

    depends_on:
      discovery-server:
        condition: service_started

      config-server:
        condition: service_healthy

    networks:
      - classy-network

  product-service:

    build:
      context: ./product-service

    container_name: classy-product-service
    restart: always

    ports:
      - "8081:8081"
      - "5005:5005"

    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "-f",
          "http://localhost:8081/actuator/health"
        ]

      interval: 10s
      timeout: 5s
      retries: 10

    depends_on:
      product-postgres:
        condition: service_healthy

      discovery-server:
        condition: service_started

      config-server:
        condition: service_healthy

    networks:
      - classy-network

volumes:
  product_postgres_data:
  redis_data:
  kafka_data:

networks:
  classy-network:
    name: classy-network