spring:
  application:
    name: payment-service

  config:
    import: configserver:http://classy-config-server:8888

server:
  port: 8084

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true

    service-url:
      defaultZone: http://classy-discovery-server:8761/eureka/