spring:
  application:
    name: product-service

eureka:
  instance:
    hostname: classy-product-service
    prefer-ip-address: false

  config:
    import: configserver:http://classy-config-server:8888

server:
  port: 8081