server:
  port: 8080

spring:
  cloud:
    gateway:
      routes: []

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://classy-discovery-server:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus