server:
  port: 8080

spring:
  cloud:
    gateway:
      routes: []

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://classy-discover-server:8761/eureka/
