server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: product-service
          uri: http://classy-product-service:8081
          predicates:
            - Path=/products/**
          filters:
            - StripPrefix=1
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://classy-discovery-server:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus