spring:
  application:
    name: inventory-service

  datasource:
    url: jdbc:postgresql://classy-inventory-postgres:5432/inventorydb             #using db with service-name not localhost
    username: postgres
    password: postgres123

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://classy-discovery-server:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus