spring:
  application:
    name: product-service

  datasource:
    url: jdbc:postgresql://classy-postgres:5432/productdb             #using db with service-name not localhost
    username: postgres
    password: postgres123