spring:
  application:
    name: product-service

  datasource:
    url: jdbc:postgresql://classy-product-postgres:5432/productdb             #using db with service-name not localhost
    username: postgres
    password: postgres123

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

eureka:
  client:
    service-url:
      defaultZone: http://classy-discovery-server:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus